'use strict';
// Published, crawlable pages for the parts of the corpus that are PUBLIC INSTRUMENTS.
//
// Why: on 2026-09-12 a site: search for bina.et returned nothing, and the corpus that makes
// BinaSmart unique — Ethiopian health entitlements — was reachable only by asking a chatbot. A
// crawler cannot ask a chatbot. The questions it answers ("is delivery free?", "which hospital does
// caesarean sections?") are exactly what people type into a search box.
//
// DELIBERATELY NOT PUBLISHED, and must stay out:
//   • ES 3611, ES 7192:2025, ES 7193:2025 — the Ethiopian Standards Agency SELLS these. Answering a
//     question from them is one thing; republishing them whole is redistributing a paid product.
//   • criminal-law-procedure-training.md — a third party's training material, not a statute.
//   • fdre-constitution.md, federal-courts-proclamation-1234-2021.md — both carry OCR damage
//     (self-detennination, obj~tives, and legacy-font Amharic bleeding into the English column as
//     ›.M / ±.œ.q.Ü). Publishing corrupted text AS LAW would destroy the only thing that makes it
//     worth having. They stay in the assistant, where every answer is hedged and cited.
//
// Published: the Essential Health Services Package annex — Ethiopian government policy, and the
// sentences were generated by ops/health/ehsp-annex.py from the official table, so they are clean
// prose rather than OCR output.
const fs = require('fs');
const path = require('path');

const SOURCE = {
  file: 'knowledge/health/ehsp-annex-service-levels-2019.md',
  document: 'Essential Health Services Package of Ethiopia (November 2019), Annex II, Table 19',
  authority: 'Ministry of Health of Ethiopia',
  sourceUrl: 'https://www.moh.gov.et/',
};

const LEVELS = ['health posts', 'health centres', 'primary hospitals', 'general hospitals', 'tertiary hospitals'];
const PAYMENT = { 'free of charge': 'Free', 'on a cost-sharing basis': 'Cost sharing', 'on a cost-recovery basis': 'Cost recovery' };

const slugify = s => String(s).toLowerCase().normalize('NFKD')
  .replace(/[^a-z0-9\s-]/g, ' ').replace(/\s+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60);

let CACHE = null;
function load(root) {
  if (CACHE) return CACHE;
  const raw = fs.readFileSync(path.join(root, SOURCE.file), 'utf8');
  const body = raw.replace(/^---[\s\S]*?\n---\n/, '');
  const groups = new Map();

  for (const line of body.split('\n')) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    // Each line carries its own programme in parentheses — group on THAT, not on the ## headings,
    // which the converter sometimes guessed from wrapped table text ("ACE inhibitors, and
    // mineralocorticoid antagonists" is an intervention, not a programme area). Using the data on
    // the line is self-validating and discards the bad headings for free.
    const m = /^(.+?)\s*\(([^)]*)\)\s*(?:is provided at (.+?))?\s*(?:,\s*(free of charge|on a cost-sharing basis|on a cost-recovery basis))?\.\s*$/.exec(t);
    if (!m) continue;
    const [, name, context, levelsRaw, pay] = m;
    const programme = context.split(';')[0].trim();
    const sub = (context.split(';')[1] || '').trim();
    if (!programme || programme.length > 60) continue;
    const levels = LEVELS.filter(l => (levelsRaw || '').includes(l));
    const key = programme.toLowerCase();
    if (!groups.has(key)) groups.set(key, { name: programme, items: [] });
    groups.get(key).items.push({ name: name.trim(), sub, levels, payment: PAYMENT[pay] || '' });
  }

  // The programme label on each line came from ops/health/ehsp-annex.py, whose heading detector
  // sometimes mistook wrapped table text for a programme area — which is why "ACE inhibitors, and
  // mineralocorticoid antagonists" and "Psychoeducation reduces relapse, readmission" appear
  // beside RMNCH and NCD. Those are interventions, not programmes.
  //
  // No heuristic separates them cleanly — the real names are as varied as the false ones
  // ("Livestock sector" and "Breastfeeding women" look exactly like sentence fragments). So the
  // genuine programme areas are named here explicitly. It is a stopgap; the honest fix is to repair
  // the converter's heading detection and regenerate, which would improve the corpus too.
  const REAL = new Set(['rmnch', 'ncd', 'ntd', 'hiv/aids, tb, and malaria', 'breastfeeding women',
    'surgical, emergency, and critical care', 'health education and promotion', 'livestock sector',
    'multi-sectoral environmental health and hygiene', 'mental, neurological and substance use disorders']);
  const pages = [...groups.values()]
    .filter(g => g.items.length >= 3 && REAL.has(g.name.toLowerCase().replace(/\s+/g, ' ').trim()))
    .map(g => ({ ...g, slug: slugify(g.name), count: g.items.length }))
    .sort((a, b) => b.count - a.count);
  CACHE = { pages, source: SOURCE, levels: LEVELS, total: pages.reduce((n, p) => n + p.count, 0) };
  return CACHE;
}

module.exports = { load, SOURCE, LEVELS, slugify };
