'use strict';
// Collapse duplicate @font-face files in public/fonts/fonts.css.
//
// Why: vendor-fonts.js asks Google for the variable font of each family, but when a page requested
// several discrete weights it saved the SAME variable file once per weight. Plus Jakarta Sans ended
// up as five byte-identical copies under five names, so a browser downloaded 27 KB five times for one
// typeface — 108 KB of pure waste on the ride page alone.
//
// What this does: groups faces by family + style + unicode-range + file checksum, and where several
// share one file it writes a single face with the full weight range (font-weight: 400 800), keeps one
// copy of the file and deletes the orphans. Same typefaces, same weights, same look.
//
//   node ops/fonts/dedupe-fonts.js          report only
//   node ops/fonts/dedupe-fonts.js --write  rewrite fonts.css and delete the duplicate files
const fs = require('fs'), path = require('path'), crypto = require('crypto');
const PUB = path.join(__dirname, '..', '..', 'public');
const DIR = path.join(PUB, 'fonts');
const CSS = path.join(DIR, 'fonts.css');
const WRITE = process.argv.includes('--write');

const css = fs.readFileSync(CSS, 'utf8');
const faces = [];
const RE = /@font-face\{([^}]*)\}/g;
let mm;
while ((mm = RE.exec(css))) {
  const b = mm[1];
  const get = (k) => { const r = new RegExp(k + ':\\s*([^;]+)').exec(b); return r ? r[1].trim() : ''; };
  const url = /url\(([^)]+)\)/.exec(b);
  if (!url) continue;
  const file = path.basename(url[1]);
  const w = get('font-weight').split(/\s+/).map(Number).filter(n => !isNaN(n));
  faces.push({ family: get('font-family'), style: get('font-style') || 'normal', display: get('font-display') || 'swap',
    range: get('unicode-range'), file, wMin: Math.min.apply(null, w), wMax: Math.max.apply(null, w) });
}

const sums = new Map();
const sumOf = (f) => {
  if (!sums.has(f)) {
    const p = path.join(DIR, f);
    sums.set(f, fs.existsSync(p) ? crypto.createHash('md5').update(fs.readFileSync(p)).digest('hex') : 'MISSING:' + f);
  }
  return sums.get(f);
};

const groups = new Map();
for (const f of faces) {
  const key = [f.family, f.style, f.range, sumOf(f.file)].join('|');
  if (!groups.has(key)) groups.set(key, []);
  groups.get(key).push(f);
}

const keep = [], drop = [];
let saved = 0;
for (const [, g] of groups) {
  const first = g[0];
  const wMin = Math.min.apply(null, g.map(x => x.wMin));
  const wMax = Math.max.apply(null, g.map(x => x.wMax));
  keep.push(Object.assign({}, first, { wMin, wMax, merged: g.length }));
  for (const extra of g.slice(1)) {
    if (extra.file !== first.file) { drop.push(extra.file); saved += fs.existsSync(path.join(DIR, extra.file)) ? fs.statSync(path.join(DIR, extra.file)).size : 0; }
  }
}

const out = ['/* Fonts served from bina.et. Generated by ops/fonts/vendor-fonts.js, deduped by ops/fonts/dedupe-fonts.js.',
  '   One file per family + script: the variable font already carries every weight, so a face declares its',
  '   whole range (font-weight: 400 800) instead of downloading the same file once per weight. */'];
for (const f of keep) {
  const size = fs.existsSync(path.join(DIR, f.file)) ? Math.round(fs.statSync(path.join(DIR, f.file)).size / 1024) : 0;
  const wt = f.wMin === f.wMax ? String(f.wMin) : f.wMin + ' ' + f.wMax;
  out.push('/* ' + f.family.replace(/'/g, '') + ' ' + wt + ' ' + (f.range ? rangeName(f.file) : '') + ' — ' + size + ' KB' + (f.merged > 1 ? ', was ' + f.merged + ' copies' : '') + ' */');
  out.push('@font-face{font-family:' + f.family + ';font-style:' + f.style + ';font-weight:' + wt +
    ';font-display:' + f.display + ';src:url(/static/fonts/' + f.file + ") format('woff2')" +
    (f.range ? ';unicode-range:' + f.range : '') + '}');
}
function rangeName(file) { const m = /-(cyrillic-ext|cyrillic|greek-ext|greek|vietnamese|latin-ext|latin|ethiopic)-[0-9a-f]+\.woff2$/.exec(file); return m ? m[1] : ''; }

console.log('faces ' + faces.length + ' -> ' + keep.length + ', duplicate files ' + drop.length + ', saves ' + Math.round(saved / 1024) + ' KB on disk');
for (const [, g] of groups) if (g.length > 1) console.log('  merged x' + g.length + '  ' + g[0].family + ' ' + rangeName(g[0].file) + ' -> ' + g[0].file);

if (!WRITE) { console.log('\n(dry run — pass --write to apply)'); process.exit(0); }

// never delete a file another page references directly
const refs = fs.readdirSync(PUB).filter(f => f.endsWith('.html')).map(f => fs.readFileSync(path.join(PUB, f), 'utf8')).join('\n');
const unsafe = drop.filter(f => refs.includes(f));
if (unsafe.length) throw new Error('referenced outside fonts.css: ' + unsafe.join(', '));

fs.writeFileSync(CSS, out.join('\n') + '\n');
for (const f of new Set(drop)) { try { fs.unlinkSync(path.join(DIR, f)); } catch (e) {} }
console.log('written: fonts.css (' + keep.length + ' faces), removed ' + new Set(drop).size + ' files');
