'use strict';
// Serve the site's fonts from bina.et instead of Google.
//
// Why: on a weak connection the fonts are the heaviest and slowest thing on the page — the building
// page pulled 198 KB of Noto Sans Ethiopic from fonts.gstatic.com, a third host with its own DNS and
// TLS handshake, worth several seconds on 3G in Addis. Same typefaces, same weights, same look; one
// host, one handshake, long cache.
//
// What it does:
//   1. finds every fonts.googleapis.com/css2 link in public/*.html and server.js
//   2. unions the families and weights into one request per family, asking for the VARIABLE font
//      (wght@min..max) so all weights of a family arrive in one file per script instead of one file
//      per weight — for Ethiopic that is one ~200 KB file instead of three or four
//   3. downloads each woff2 into public/fonts/ and writes public/fonts/fonts.css with the same
//      @font-face blocks (unicode-range kept, so a page in Latin never downloads the Ethiopic file)
//   4. with --write, replaces the Google <link>s with the local stylesheet and drops the preconnects
//
//   node ops/fonts/vendor-fonts.js          dry run: report what would change
//   node ops/fonts/vendor-fonts.js --write  do it
const fs = require('fs'), path = require('path'), crypto = require('crypto');
const ROOT = path.join(__dirname, '..', '..');
const PUB = path.join(ROOT, 'public');
const OUT = path.join(PUB, 'fonts');
const WRITE = process.argv.includes('--write');
const LOCAL_CSS = '/static/fonts/fonts.css?v=1';
// Chrome UA so Google answers with woff2 + unicode-range blocks (older UAs get ttf without ranges)
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';

const files = fs.readdirSync(PUB).filter(f => f.endsWith('.html')).map(f => path.join(PUB, f)).concat([path.join(ROOT, 'server.js')]);
const LINK_RE = /https:\/\/fonts\.googleapis\.com\/css2\?[^"'\s>)]+/g;

// 1. inventory
const fam = new Map();   // family -> Set(weights)
const perFile = new Map();
for (const f of files) {
  const s = fs.readFileSync(f, 'utf8');
  const urls = [...s.matchAll(LINK_RE)].map(m => m[0].replace(/&amp;/g, '&'));
  if (!urls.length) continue;
  perFile.set(f, urls);
  for (const u of urls) {
    const q = new URL(u).searchParams;
    for (const spec of q.getAll('family')) {
      const [name, axes] = spec.split(':');
      const set = fam.get(name) || new Set();
      const m = axes && axes.match(/wght@([\d;.]+)/);
      if (m) m[1].split(';').forEach(w => { if (w.includes('..')) { const [a, b] = w.split('..').map(Number); for (let x = a; x <= b; x += 100) set.add(x); } else set.add(Number(w)); });
      else set.add(400);
      fam.set(name, set);
    }
  }
}
console.log('files with Google Fonts: ' + perFile.size);
for (const [n, ws] of fam) console.log('  ' + n + '  weights ' + [...ws].sort((a, b) => a - b).join(','));

// 2. one variable request per family covering the weight span the site uses
async function fetchText(u) { const r = await fetch(u, { headers: { 'user-agent': UA } }); if (!r.ok) throw new Error(r.status + ' ' + u); return r.text(); }
async function fetchBuf(u) { const r = await fetch(u, { headers: { 'user-agent': UA } }); if (!r.ok) throw new Error(r.status + ' ' + u); return Buffer.from(await r.arrayBuffer()); }

(async () => {
  let css = '/* Fonts served from bina.et — generated by ops/fonts/vendor-fonts.js. Same faces as before, one host. */\n';
  let totalBytes = 0, nFiles = 0;
  fs.mkdirSync(OUT, { recursive: true });
  for (const [name, ws] of fam) {
    const sorted = [...ws].sort((a, b) => a - b);
    const lo = sorted[0], hi = sorted[sorted.length - 1];
    const spec = lo === hi ? String(lo) : lo + '..' + hi;
    const u = 'https://fonts.googleapis.com/css2?family=' + encodeURIComponent(name).replace(/%20/g, '+') + ':wght@' + spec + '&display=swap';
    let text;
    try { text = await fetchText(u); }
    catch (e) { // not every family ships a variable axis; fall back to the static weights
      const u2 = 'https://fonts.googleapis.com/css2?family=' + encodeURIComponent(name).replace(/%20/g, '+') + ':wght@' + sorted.join(';') + '&display=swap';
      text = await fetchText(u2);
    }
    const blocks = [...text.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([\s\S]*?)\}/g)];
    if (!blocks.length) throw new Error('no @font-face blocks for ' + name);
    for (const [, subset, body] of blocks) {
      const src = body.match(/url\((https:[^)]+)\)/);
      if (!src) continue;
      const weight = (body.match(/font-weight:\s*([^;]+);/) || [])[1] || '400';
      const range = (body.match(/unicode-range:\s*([^;]+);/) || [])[1] || '';
      const slug = name.toLowerCase().replace(/\s+/g, '-') + '-' + weight.replace(/\s+/g, '-') + '-' + subset + '-' + crypto.createHash('md5').update(src[1]).digest('hex').slice(0, 6) + '.woff2';
      const dest = path.join(OUT, slug);
      if (!fs.existsSync(dest)) { const buf = await fetchBuf(src[1]); fs.writeFileSync(dest, buf); }
      const bytes = fs.statSync(dest).size; totalBytes += bytes; nFiles++;
      css += '/* ' + name + ' ' + weight + ' ' + subset + ' — ' + Math.round(bytes / 1024) + ' KB */\n@font-face{font-family:\'' + name + '\';font-style:normal;font-weight:' + weight + ';font-display:swap;src:url(/static/fonts/' + slug + ') format(\'woff2\');' + (range ? 'unicode-range:' + range + ';' : '') + '}\n';
      console.log('  ' + String(Math.round(bytes / 1024)).padStart(4) + ' KB  ' + name + ' ' + weight + ' ' + subset);
    }
  }
  fs.writeFileSync(path.join(OUT, 'fonts.css'), css);
  console.log('fonts.css written: ' + nFiles + ' files, ' + Math.round(totalBytes / 1024) + ' KB on disk (a page downloads only the scripts and families it uses)');

  // 3. rewrite the pages
  let changed = 0;
  for (const [f, urls] of perFile) {
    let s = fs.readFileSync(f, 'utf8'), before = s;
    // the stylesheet links
    s = s.replace(/<link[^>]+href="https:\/\/fonts\.googleapis\.com\/css2\?[^"]*"[^>]*>/g, '<link rel="stylesheet" href="' + LOCAL_CSS + '">');
    s = s.replace(/<link[^>]+href='https:\/\/fonts\.googleapis\.com\/css2\?[^']*'[^>]*>/g, '<link rel="stylesheet" href="' + LOCAL_CSS + '">');
    // four pages pull fonts with a CSS @import inside <style>; an @import is render-blocking and
    // serial, so drop it and make sure the page carries the ordinary <link> instead
    if (/@import\s+url\(['"]?https:\/\/fonts\.googleapis\.com\/css2\?[^)]*\)\s*;?/.test(s)) {
      s = s.replace(/[ \t]*@import\s+url\(['"]?https:\/\/fonts\.googleapis\.com\/css2\?[^)]*\)\s*;?[ \t]*\n?/g, '');
      if (!s.includes(LOCAL_CSS)) s = s.replace(/(<meta charset=[^>]+>)/i, '$1\n<link rel="stylesheet" href="' + LOCAL_CSS + '">');
    }
    // preconnects to hosts we no longer talk to
    s = s.replace(/\s*<link[^>]+rel="preconnect"[^>]+fonts\.(googleapis|gstatic)\.com[^>]*>/g, '');
    s = s.replace(/\s*<link[^>]+fonts\.(googleapis|gstatic)\.com[^>]+rel="preconnect"[^>]*>/g, '');
    // a page that had two Google links now has the local link twice — keep one
    const first = s.indexOf(LOCAL_CSS); if (first >= 0) s = s.slice(0, first + 1) + s.slice(first + 1).replace(new RegExp('\\s*<link rel="stylesheet" href="' + LOCAL_CSS.replace(/[?.]/g, '\\$&') + '">', 'g'), '');
    if (s !== before) { changed++; if (WRITE) fs.writeFileSync(f, s); }
    const left = (s.match(/fonts\.(googleapis|gstatic)\.com/g) || []).length;
    if (left) console.log('  !! still references Google Fonts after rewrite: ' + path.basename(f) + ' (' + left + ')');
  }
  console.log((WRITE ? 'rewrote ' : 'would rewrite ') + changed + ' files');
  if (!WRITE) console.log('dry run — re-run with --write to apply');
})().catch(e => { console.error(e.message); process.exit(1); });
